title: DIPI SITE
description: >-
  Site vitrine de l'Ã©quipe DIPI au sein du CEREMA
baseurl: "/dipisite"
url: "https://betagouv.github.io/"

# Build settings
plugins:
  - jekyll-feed

collections:
  startups:
    output: true
    permalink: /startups/:title.html

defaults:
  - scope:
      path: ""
      type: "startups"
    values:
      layout: startup
